steps:

# Pull the sast-scan image from the container registry. Feel free to cache it locally within acr, ecr or gcr to
# improve performance and security
- script: docker pull cincan/clamav:latest
  displayName: "Download clamav"
- script: |
    docker run \
      -v "$(Build.SourcesDirectory):/app" \
      -v "$(Build.ArtifactStagingDirectory):/reports" \
      cincan/clamav -i -r  /app 
  displayName: "Perform Scan"
  continueOnError: "true"
