steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'
- script: |
    rm -rf node_modules package-lock.json
    npm cache clean --force
    npm install --force
    #npm install
    #rm package-lock.json
    #npm install
  displayName: 'npm install'
- task: OWASPDependencyCheck@0
  inputs:
    outputDirectory: '$(Agent.TempDirectory)/dependency-scan-results'
    scanDirectory: '$(Build.SourcesDirectory)'
    outputFormat: 'ALL'
    #useSonarQubeIntegration: true
