steps:
              - task: DownloadPipelineArtifact@2
                displayName: Download Build Artifacts - ADF ARM templates
                inputs:
                  artifactName: '$(CommonPublishArmTemplateName)'
                  targetPath: '$(WorkspaceArmTemplateDirectory)'
              - script: dir
                displayName: List files in Workspace
                workingDirectory: '$(WorkspaceArmTemplateDirectory)'

              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploying to Dev RG task'
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: '$(azure_service_connection_name)'
                  subscriptionId: '$(azure_subscription_id)'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(resource_group_name)'
                  location: '$(ADF_LOCATION)'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(WorkspaceArmTemplateDirectory)/ARMTemplateForFactory.json'
                  csmParametersFile: '$(WorkspaceArmTemplateDirectory)/ARMTemplateParametersForFactory.json'
                  overrideParameters: '-name ${{ parameters.ADF_NAME }} -location ${{ parameters.ADF_LOCATION }} -apiVersion 2023-07-06'
                  #overrideParameters: '-factoryName "$(DevAdfName)" -LS_SalesDatabase_connectionString "$(DevSalesDbConnectionString)" -LS_DataLake_properties_typeProperties_url "$(DevDataLakeUrl)" -LS_KeyVault_properties_typeProperties_baseUrl "$(DevKeyVaultBaseUrl)"'
                  deploymentMode: 'Incremental'