steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          abdulbasit@analytics.com.pk
         
        instructions: 'Please validate the build configuration and E2E Docker Cypress results and resume to deploy on QA Environment'
        environment: 'SQA'
        #onTimeout: 'resume'
        onTimeout: 'reject'
